- name: Verify apache installation
  hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Write the apache config file
      ansible.builtin.template:
        src: /srv/httpd.j2
        dest: /etc/httpd.conf
      notify:
        - Restart apache

    - name: Ensure apache is running
      ansible.builtin.service:
        name: httpd
        state: started

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted


# tasks:
#   - name: Restart everything
#     command: echo "this task will restart the web services"
#     notify: "restart web services"

# handlers:
#   - name: Restart memcached
#     service:
#       name: memcached
#       state: restarted
#     listen: "restart web services"

#   - name: Restart apache
#     service:
#       name: apache
#       state: restarted
#     listen: "restart web services"